-- MySQL 数据库 schema
-- 转换命令：
-- 1. 修改 prisma/schema.prisma 中的 provider = "mysql"
-- 2. 修改 .env 中的 DATABASE_URL 为 MySQL 连接串
-- 3. 运行 npx prisma db push

CREATE TABLE IF NOT EXISTS User (
    id VARCHAR(36) PRIMARY KEY,
    username VARCHAR(100) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    name VARCHAR(100),
    role VARCHAR(20) NOT NULL DEFAULT 'operator',
    isActive BOOLEAN NOT NULL DEFAULT true,
    createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS DeviceType (
    id VARCHAR(36) PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    description TEXT,
    customAttributes JSON,
    createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS Station (
    id VARCHAR(36) PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    description TEXT,
    positionX INT NOT NULL DEFAULT 0,
    positionY INT NOT NULL DEFAULT 0,
    createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS Counter (
    id VARCHAR(36) PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    stationId VARCHAR(36),
    description TEXT,
    createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (stationId) REFERENCES Station(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS Device (
    id VARCHAR(36) PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    deviceTypeId VARCHAR(36),
    counterId VARCHAR(36),
    status VARCHAR(20) NOT NULL DEFAULT 'idle',
    customData JSON,
    createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (deviceTypeId) REFERENCES DeviceType(id) ON DELETE SET NULL,
    FOREIGN KEY (counterId) REFERENCES Counter(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS DeviceChangeRecord (
    id VARCHAR(36) PRIMARY KEY,
    deviceId VARCHAR(36) NOT NULL,
    fromStationId VARCHAR(36),
    toStationId VARCHAR(36),
    fromCounterId VARCHAR(36),
    toCounterId VARCHAR(36),
    changeType VARCHAR(50) NOT NULL,
    reason TEXT,
    operatorId VARCHAR(36),
    createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (deviceId) REFERENCES Device(id) ON DELETE CASCADE,
    FOREIGN KEY (operatorId) REFERENCES User(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS PaperChangeRecord (
    id VARCHAR(36) PRIMARY KEY,
    deviceId VARCHAR(36) NOT NULL,
    paperType VARCHAR(100) NOT NULL,
    changeType VARCHAR(50) NOT NULL,
    operatorId VARCHAR(36),
    createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (deviceId) REFERENCES Device(id) ON DELETE CASCADE,
    FOREIGN KEY (operatorId) REFERENCES User(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS ConsumableRecord (
    id VARCHAR(36) PRIMARY KEY,
    deviceId VARCHAR(36) NOT NULL,
    consumableType VARCHAR(100) NOT NULL,
    quantity INT NOT NULL,
    operatorId VARCHAR(36),
    createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (deviceId) REFERENCES Device(id) ON DELETE CASCADE,
    FOREIGN KEY (operatorId) REFERENCES User(id) ON DELETE SET NULL
);
